openapi: 3.0.0
info:
  description: LOG Restful api.
  version: 1.0.0
  title: LOG Backend
paths:
  /log:
    get:
      tags:
        - logs
      summary: get log
      description: get list of logs
      parameters:
        - level: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - message: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - resourceId: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - timestamp: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - traceId: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - spanId: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - commit: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
        - parentResourceId: code
          in: path
          required: true
          description: State code to be searched.
          schema:
            type: string
      responses:
        '200':
          description: log get successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
    post:
      tags:
        - logs
      summary: insert log
      description: insert log
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - level
                - message
                - resourceId
                - timestamp
                - traceId
                - spanId
                - commit
                - metadata
              properties:
                level:
                  type: string
                message:
                  type: string
                resourceId:
                  type: string
                timestamp:
                  type: string
                traceId:
                  type: string
                spanId:
                  type: string
                commit:
                  type: string
                metadata:
                  type: object
                  properties:
                    parentResourceId:
                      type: string
      responses:
        '201':
          description: User login successfuly
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
components:
  schemas:
    response:
      properties:
        status:
          type: string
        code:
          type: number
        message:
          type: string
        data:
          type: object
